package codegen

import (
	"bytes"
	"fmt"
	"runtime"
	"strings"

	"github.com/jeffscottbrown/ripple-lang/internal/ast"
)

// typedVal pairs an LLVM value reference with its LLVM type string.
type typedVal struct {
	v string // value reference, e.g. "%tmp.3" or "42"
	t string // type string, e.g. "i1", "i32", "i8*"
}

// Compiler translates a Ripple AST into LLVM IR text.
type Compiler struct {
	globals bytes.Buffer        // global string constant declarations
	fn      bytes.Buffer        // main() body – all basic blocks written in order
	strs    map[string]string   // interned string literals → global variable name
	vars    map[string]bool     // variables that have already been alloca'd
	names   map[string]string   // populated from "circle of friends" section
	albums  map[string][]string // populated from "albums" section
	strIdx  int                 // next index for naming .str globals
	condIdx int                 // next index for naming conditional basic block labels
	tmpIdx  int                 // next index for naming unnamed temporaries
}

// NewCompiler returns a fresh, ready-to-use Compiler.
func NewCompiler() *Compiler {
	return &Compiler{}
}

// Compile translates prog into an LLVM IR module and returns the module as a
// string.  The compiler may be reused; all state is reset on each call.
func (c *Compiler) Compile(prog *ast.Program) string {
	c.globals.Reset()
	c.fn.Reset()
	c.strs = make(map[string]string)
	c.vars = make(map[string]bool)
	c.names = make(map[string]string)
	c.albums = make(map[string][]string)
	c.strIdx = 0
	c.condIdx = 0
	c.tmpIdx = 0

	// Pre-pass: populate names and albums from their respective sections before
	// any code is emitted, so that jam-block statements can reference them.
	for _, sec := range prog.Sections {
		switch sec.Name {
		case "circle of friends":
			for _, e := range sec.Entries {
				c.names[e.Key] = e.Value
			}
		case "albums":
			for _, e := range sec.Entries {
				c.albums[e.Key] = e.Collection
			}
		}
	}

	// Emit all jam-section statements into the function body.  String globals
	// are collected into c.globals as they are encountered.
	c.fn.WriteString("entry:\n")
	for _, sec := range prog.Sections {
		if sec.Name == "jam" {
			c.emitStatements(sec.Statements)
		}
	}
	c.fn.WriteString("  ret i32 0\n")

	// Assemble the final module: comment, globals, external decls, main().
	var out bytes.Buffer
	out.WriteString("; Generated by the Ripple compiler\n\n")
	if triple := targetTriple(); triple != "" {
		fmt.Fprintf(&out, "target triple = \"%s\"\n\n", triple)
	}
	out.WriteString(c.globals.String())
	if c.globals.Len() > 0 {
		out.WriteString("\n")
	}
	out.WriteString("declare i32 @printf(i8* nocapture, ...)\n\n")
	out.WriteString("define i32 @main() {\n")
	out.WriteString(c.fn.String())
	out.WriteString("}\n")
	return out.String()
}

// ── Statement emission ────────────────────────────────────────────────────────

func (c *Compiler) emitStatements(stmts []*ast.Statement) {
	for _, s := range stmts {
		c.emitStatement(s)
	}
}

func (c *Compiler) emitStatement(s *ast.Statement) {
	switch {
	case s.Print != nil:
		c.emitPrint(s.Print)
	case s.Assignment != nil:
		c.emitAssignment(s.Assignment)
	case s.Conditional != nil:
		c.emitConditional(s.Conditional)
	}
}

// emitPrint handles the `say` statement, routing all output through printf.
//
// Each argument is evaluated via emitTerm. A format string is constructed
// with one "%s" per i8* argument and one "%d" per numeric argument, followed
// by an actual newline byte. The format string is interned as a global
// constant, and a single printf call is emitted.
func (c *Compiler) emitPrint(p *ast.Print) {
	// Evaluate every argument and collect typed values.
	var args []typedVal
	for _, arg := range p.Args {
		args = append(args, c.emitTerm(arg.Left))
	}

	// Build the format string.
	var fmtBuf strings.Builder
	for _, a := range args {
		if a.t == "i8*" {
			fmtBuf.WriteString("%s")
		} else {
			fmtBuf.WriteString("%d")
		}
	}
	fmtBuf.WriteByte('\n') // actual newline byte – llvmEscapeString will turn it into \0A
	fmtStr := fmtBuf.String()

	// Intern the format string and obtain a pointer to it.
	fmtName, fmtSize := c.internString(fmtStr)
	fmtTmp := c.nextTmp()
	fmt.Fprintf(&c.fn,
		"  %%%s = getelementptr inbounds [%d x i8], [%d x i8]* @%s, i32 0, i32 0\n",
		fmtTmp, fmtSize, fmtSize, fmtName)

	// Emit the printf call.
	var call strings.Builder
	fmt.Fprintf(&call, "  call i32 (i8*, ...) @printf(i8* %%%s", fmtTmp)
	for _, a := range args {
		fmt.Fprintf(&call, ", %s %s", a.t, a.v)
	}
	call.WriteString(")\n")
	c.fn.WriteString(call.String())
}

// emitAssignment handles `target becomes expr`.
func (c *Compiler) emitAssignment(a *ast.Assignment) {
	// Emit alloca only once per variable name.
	if !c.vars[a.Target] {
		fmt.Fprintf(&c.fn, "  %%%s = alloca i1, align 1\n", a.Target)
		c.vars[a.Target] = true
	}
	val := c.emitExpr(a.Value)
	fmt.Fprintf(&c.fn, "  store i1 %s, i1* %%%s, align 1\n", val, a.Target)
}

// emitConditional handles `suppose cond body [otherwise body] enough`.
//
// Block layout (no else):
//
//	<current block>  →  br cond, then.N, merge.N
//	then.N           →  body; br merge.N
//	merge.N          →  <fall-through for subsequent statements>
//
// Block layout (with else):
//
//	<current block>  →  br cond, then.N, else.N
//	then.N           →  body; br merge.N
//	else.N           →  otherwise; br merge.N
//	merge.N          →  <fall-through for subsequent statements>
func (c *Compiler) emitConditional(cond *ast.Conditional) {
	idx := c.condIdx
	c.condIdx++

	thenLabel := fmt.Sprintf("then.%d", idx)
	mergeLabel := fmt.Sprintf("merge.%d", idx)

	condVal := c.emitExpr(cond.Condition)

	if cond.Otherwise != nil {
		elseLabel := fmt.Sprintf("else.%d", idx)
		fmt.Fprintf(&c.fn, "  br i1 %s, label %%%s, label %%%s\n", condVal, thenLabel, elseLabel)

		fmt.Fprintf(&c.fn, "%s:\n", thenLabel)
		c.emitStatements(cond.Body)
		fmt.Fprintf(&c.fn, "  br label %%%s\n", mergeLabel)

		fmt.Fprintf(&c.fn, "%s:\n", elseLabel)
		c.emitStatements(cond.Otherwise)
		fmt.Fprintf(&c.fn, "  br label %%%s\n", mergeLabel)
	} else {
		fmt.Fprintf(&c.fn, "  br i1 %s, label %%%s, label %%%s\n", condVal, thenLabel, mergeLabel)

		fmt.Fprintf(&c.fn, "%s:\n", thenLabel)
		c.emitStatements(cond.Body)
		fmt.Fprintf(&c.fn, "  br label %%%s\n", mergeLabel)
	}

	// Subsequent instructions are emitted into the merge block.
	fmt.Fprintf(&c.fn, "%s:\n", mergeLabel)
}

// ── Expression emission ───────────────────────────────────────────────────────

// emitExpr evaluates expr in the current basic block, emitting any required
// instructions, and returns a plain string for the LLVM i1 result (a named
// register such as "%tmp.3" or a bare literal "0"/"1").
func (c *Compiler) emitExpr(expr *ast.Expression) string {
	// The "has" operator is resolved entirely at compile time against c.albums;
	// no LLVM instructions are emitted.
	if expr.Op == "has" {
		var artistName string
		switch {
		case expr.Left.Ident != nil:
			artistName = *expr.Left.Ident
		case expr.Left.Attr != nil:
			artistName = expr.Left.Attr.Name
		}
		if expr.Right != nil && expr.Right.Str != nil {
			want := *expr.Right.Str
			for _, have := range c.albums[artistName] {
				if have == want {
					return "1"
				}
			}
		}
		return "0"
	}

	left := c.emitTerm(expr.Left)
	if expr.Op == "" {
		return left.v
	}

	right := c.emitTerm(expr.Right)
	result := c.nextTmp()
	switch expr.Op {
	case "vibes_like":
		fmt.Fprintf(&c.fn, "  %%%s = icmp eq %s %s, %s\n", result, left.t, left.v, right.v)
	case "harshing_the_vibe_of":
		fmt.Fprintf(&c.fn, "  %%%s = icmp ne %s %s, %s\n", result, left.t, left.v, right.v)
	case "louder_than":
		fmt.Fprintf(&c.fn, "  %%%s = icmp sgt %s %s, %s\n", result, left.t, left.v, right.v)
	case "quieter_than":
		fmt.Fprintf(&c.fn, "  %%%s = icmp slt %s %s, %s\n", result, left.t, left.v, right.v)
	case "and":
		fmt.Fprintf(&c.fn, "  %%%s = and i1 %s, %s\n", result, left.v, right.v)
	case "or":
		fmt.Fprintf(&c.fn, "  %%%s = or i1 %s, %s\n", result, left.v, right.v)
	default:
		// Unknown operator – conservatively return false.
		return "0"
	}
	return "%" + result
}

// emitAttr materialises an attribute access (e.g. jerry.name, jerry.albumcount)
// and returns a typed value.
//
//   - .name      → look up c.names, intern the string, return i8* GEP result
//   - .albumcount → len(c.albums[name]) as a compile-time i32 constant
//   - anything else → i32 zero
func (c *Compiler) emitAttr(attr *ast.Attr) typedVal {
	switch attr.Prop {
	case "name":
		s := c.names[attr.Name]
		name, size := c.internString(s)
		tmp := c.nextTmp()
		fmt.Fprintf(&c.fn,
			"  %%%s = getelementptr inbounds [%d x i8], [%d x i8]* @%s, i32 0, i32 0\n",
			tmp, size, size, name)
		return typedVal{"%" + tmp, "i8*"}

	case "albumcount":
		n := len(c.albums[attr.Name])
		return typedVal{fmt.Sprintf("%d", n), "i32"}

	default:
		return typedVal{"0", "i32"}
	}
}

// emitTerm emits any instructions needed to materialise a Term's value and
// returns the resulting typed LLVM value.
func (c *Compiler) emitTerm(t *ast.Term) typedVal {
	switch {
	case t.Bool != nil:
		if *t.Bool == "copacetic" {
			return typedVal{"1", "i1"}
		}
		return typedVal{"0", "i1"}

	case t.Ident != nil:
		tmp := c.nextTmp()
		fmt.Fprintf(&c.fn, "  %%%s = load i1, i1* %%%s, align 1\n", tmp, *t.Ident)
		return typedVal{"%" + tmp, "i1"}

	case t.Str != nil:
		name, size := c.internString(*t.Str)
		tmp := c.nextTmp()
		fmt.Fprintf(&c.fn,
			"  %%%s = getelementptr inbounds [%d x i8], [%d x i8]* @%s, i32 0, i32 0\n",
			tmp, size, size, name)
		return typedVal{"%" + tmp, "i8*"}

	case t.Attr != nil:
		return c.emitAttr(t.Attr)
	}

	return typedVal{"0", "i32"}
}

// ── Helpers ───────────────────────────────────────────────────────────────────

// internString registers s as a private LLVM string global (exactly once) and
// returns its global name (without the leading @) together with its total byte
// size including the null terminator.
func (c *Compiler) internString(s string) (name string, size int) {
	size = len(s) + 1 // +1 for the null terminator
	if n, ok := c.strs[s]; ok {
		return n, size
	}
	name = fmt.Sprintf(".str.%d", c.strIdx)
	c.strIdx++
	c.strs[s] = name
	fmt.Fprintf(&c.globals,
		"@%s = private unnamed_addr constant [%d x i8] c\"%s\\00\", align 1\n",
		name, size, llvmEscapeString(s))
	return name, size
}

// nextTmp allocates and returns the next unique temporary register name
// (without the leading %).
func (c *Compiler) nextTmp() string {
	name := fmt.Sprintf("tmp.%d", c.tmpIdx)
	c.tmpIdx++
	return name
}

// targetTriple returns the LLVM target triple for the current host platform,
// or an empty string on unrecognised platforms.
func targetTriple() string {
	switch runtime.GOOS {
	case "darwin":
		switch runtime.GOARCH {
		case "amd64":
			return "x86_64-apple-darwin"
		case "arm64":
			return "arm64-apple-darwin"
		}
	case "linux":
		switch runtime.GOARCH {
		case "amd64":
			return "x86_64-pc-linux-gnu"
		case "arm64":
			return "aarch64-linux-gnu"
		}
	}
	return ""
}

// llvmEscapeString escapes a Go string for use inside an LLVM IR c"…" literal.
func llvmEscapeString(s string) string {
	var b strings.Builder
	for _, ch := range []byte(s) {
		switch ch {
		case '\n':
			b.WriteString("\\0A")
		case '\r':
			b.WriteString("\\0D")
		case '"':
			b.WriteString("\\22")
		case '\\':
			b.WriteString("\\5C")
		default:
			if ch < 0x20 || ch > 0x7e {
				fmt.Fprintf(&b, "\\%02X", ch)
			} else {
				b.WriteByte(ch)
			}
		}
	}
	return b.String()
}
