package codegen

import (
	"bytes"
	"errors"
	"fmt"
	"runtime"
	"strings"

	"github.com/jeffscottbrown/ripple-lang/internal/ast"
)

const targetOSDarwin = "darwin"

// Static error definitions to satisfy err113.
var (
	ErrDuplicateSection = errors.New("duplicate section")
	ErrInvalidFriend    = errors.New("artist cannot be a collection in the circle of friends")
	ErrUndefined        = errors.New("variable for artist is not defined")
	ErrUnknownArtist    = errors.New("artist is not in your circle of friends")
	ErrInvalidProperty  = errors.New("artist does not have that property")
)

type typedVal struct {
	t string
	v string
}

type Compiler struct {
	fn      strings.Builder
	globals strings.Builder
	names   map[string]string
	albums  map[string][]string
	vars    map[string]bool
	tmpIdx  int
	strIdx  int
}

func New() *Compiler {
	return &Compiler{
		names:  make(map[string]string),
		albums: make(map[string][]string),
		vars:   make(map[string]bool),
	}
}

func (c *Compiler) Compile(prog *ast.Program) (string, error) {
	c.reset()

	// PHASE 1: DATA COLLECTION
	if err := c.collectData(prog); err != nil {
		return "", err
	}

	// PHASE 2: SEMANTIC VALIDATION
	for _, sec := range prog.Sections {
		if sec.Jam != nil {
			if err := c.validateStatements(sec.Jam.Statements, make(map[string]bool)); err != nil {
				return "", err
			}
		}
	}

	// PHASE 3: IR EMISSION
	c.fn.WriteString("define i32 @main() {\nentry:\n")
	for _, sec := range prog.Sections {
		if sec.Jam != nil {
			c.emitStatements(sec.Jam.Statements)
		}
	}
	c.fn.WriteString("  ret i32 0\n}\n")

	return c.assembleModule(), nil
}

func (c *Compiler) collectData(prog *ast.Program) error {
	seen := make(map[string]bool)
	for _, sec := range prog.Sections {
		var name string
		switch {
		case sec.Friends != nil:
			name = "circle of friends"
			if seen[name] {
				return fmt.Errorf("%w: [%s]", ErrDuplicateSection, name)
			}
			for _, e := range sec.Friends.Entries {
				c.names[e.Key] = e.Value
			}
		case sec.Albums != nil:
			name = "albums"
			if seen[name] {
				return fmt.Errorf("%w: [%s]", ErrDuplicateSection, name)
			}
			for _, e := range sec.Albums.Entries {
				c.albums[e.Key] = e.Collection
			}
		case sec.Jam != nil:
			name = "jam"
			if seen[name] {
				return fmt.Errorf("%w: [%s]", ErrDuplicateSection, name)
			}
		}
		seen[name] = true
	}
	return nil
}

func (c *Compiler) assembleModule() string {
	var out bytes.Buffer
	out.WriteString("; Generated by the Ripple compiler\n\n")
	fmt.Fprintf(&out, "target triple = \"%s\"\n\n", targetTriple())
	out.WriteString(c.globals.String())
	out.WriteString("\n")
	out.WriteString("declare i32 @printf(i8* nocapture, ...)\n")
	out.WriteString("declare i32 @fprintf(i8*, i8* nocapture, ...)\n")
	out.WriteString("declare i32 @fflush(i8*)\n")

	if runtime.GOOS == targetOSDarwin {
		out.WriteString("@__stderrp = external global i8*\n\n")
	} else {
		out.WriteString("@stderr = external global i8*\n\n")
	}
	out.WriteString(c.fn.String())
	return out.String()
}

func (c *Compiler) reset() {
	c.fn.Reset()
	c.globals.Reset()
	c.tmpIdx = 0
	c.strIdx = 0
	c.names = make(map[string]string)
	c.albums = make(map[string][]string)
	c.vars = make(map[string]bool)
}

func (c *Compiler) internString(s string) (string, int) {
	name := fmt.Sprintf(".str.%d", c.strIdx)
	c.strIdx++
	size := len(s)
	size -= (strings.Count(s, "\\00") * 2)
	size -= (strings.Count(s, "\\0A") * 2)
	fmt.Fprintf(&c.globals, "@%s = private unnamed_addr constant [%d x i8] c\"%s\", align 1\n",
		name, size, s)
	return name, size
}

func (c *Compiler) nextTmp() string {
	t := fmt.Sprintf("tmp.%d", c.tmpIdx)
	c.tmpIdx++
	return t
}

func targetTriple() string {
	switch runtime.GOOS {
	case targetOSDarwin:
		if runtime.GOARCH == "amd64" {
			return "x86_64-apple-darwin"
		}
		return "arm64-apple-darwin"
	default:
		return "x86_64-unknown-linux-gnu"
	}
}
